/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.AgendamentoController;
import java.text.ParseException;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author renea
 */
public class Agenda extends javax.swing.JFrame {
    
    private final AgendamentoController controller;
    
    
    /**
     * Creates new form AgendaAvaliacao
     */
    public Agenda() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        fieldFormatDate();
        controller = new AgendamentoController(this);
        iniciarAgenda();
 
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPesquisarAgendamento = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jComboBoxProfessor = new javax.swing.JComboBox<>();
        jButtonIprimir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAgendar = new javax.swing.JButton();
        jButtonCancelarAgendamento = new javax.swing.JButton();
        jButtonBuscarAluno = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonRefresh1 = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelProfessor = new javax.swing.JLabel();
        jLabelTextAgendarAvaliacao = new javax.swing.JLabel();
        jScrollPaneAgendaMarcada = new javax.swing.JScrollPane();
        jTableAgendaAluno = new javax.swing.JTable();
        jScrollPaneAgenda = new javax.swing.JScrollPane();
        jTableAgendaMarcados = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Opcao = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        opcaoTrocarConta = new javax.swing.JMenuItem();
        OpcaoSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPesquisarAgendamento.setPreferredSize(new java.awt.Dimension(74, 26));
        getContentPane().add(jTextFieldPesquisarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 30));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, 30));
        getContentPane().add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 130, 30));

        jComboBoxProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 30));

        jButtonIprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imprimir.png"))); // NOI18N
        getContentPane().add(jButtonIprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jButtonAgendar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jButtonCancelarAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancelarAgendamento.setText("Cancelar Agendamento");
        jButtonCancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jButtonBuscarAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuscarAluno.setText("Buscar");
        jButtonBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 30));

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refersh.png"))); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 40, 30));

        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButtonRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refersh.png"))); // NOI18N
        jButtonRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 40, 30));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNome.setText("Aluno:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(204, 204, 204));
        jLabelData.setText("Data/ Hora");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabelProfessor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProfessor.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProfessor.setText("Professor");
        getContentPane().add(jLabelProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabelTextAgendarAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTextAgendarAvaliacao.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextAgendarAvaliacao.setText("Agenda");
        getContentPane().add(jLabelTextAgendarAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jTableAgendaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "tel", "cel", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAgendaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAgendaAlunoMouseClicked(evt);
            }
        });
        jScrollPaneAgendaMarcada.setViewportView(jTableAgendaAluno);
        if (jTableAgendaAluno.getColumnModel().getColumnCount() > 0) {
            jTableAgendaAluno.getColumnModel().getColumn(0).setPreferredWidth(78);
            jTableAgendaAluno.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableAgendaAluno.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableAgendaAluno.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTableAgendaAluno.getColumnModel().getColumn(4).setPreferredWidth(250);
        }

        getContentPane().add(jScrollPaneAgendaMarcada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 850, 110));

        jTableAgendaMarcados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Aluno", "Data", "Professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneAgenda.setViewportView(jTableAgendaMarcados);
        if (jTableAgendaMarcados.getColumnModel().getColumnCount() > 0) {
            jTableAgendaMarcados.getColumnModel().getColumn(0).setPreferredWidth(78);
            jTableAgendaMarcados.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableAgendaMarcados.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableAgendaMarcados.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        getContentPane().add(jScrollPaneAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 850, 150));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGoundMenu (1).jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 35));

        Cadastro.setText("Matrículas");
        Cadastro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mulher.png"))); // NOI18N
        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treinador.png"))); // NOI18N
        jMenuItem2.setText("Professor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem2);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atuacao.png"))); // NOI18N
        jMenuItem8.setText("Admin");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem8);

        jMenuBar1.add(Cadastro);

        Opcao.setText("Opções");
        Opcao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agenda-icon.png"))); // NOI18N
        jMenuItem9.setText("Agenda");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Treino.png"))); // NOI18N
        jMenuItem10.setText("Treinos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Matricula.png"))); // NOI18N
        jMenuItem11.setText("Avaliação");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem11);

        opcaoTrocarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troca.png"))); // NOI18N
        opcaoTrocarConta.setText("Trocar de conta");
        opcaoTrocarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTrocarContaActionPerformed(evt);
            }
        });
        Opcao.add(opcaoTrocarConta);

        OpcaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        OpcaoSair.setText("Sair");
        OpcaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoSairActionPerformed(evt);
            }
        });
        Opcao.add(OpcaoSair);

        jMenuBar1.add(Opcao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Voltar ao menu principal:
        this.controller.voltarMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abre a aba Cadastrar Aluo

        this.controller.abrirCadAluno();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Abre a aba Cadastrar Professor
        this.controller.abrirCadProf();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //Abre a aba Cadastrar Adm
        this.controller.abrirCadAdm();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // Abre a aba Agenda

        this.controller.abrirAgendaAvali();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // Abre a aba Treinos

        this.controller.abrirTreinos();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // Abre a aba avaliação

        this.controller.abrirAvaliacao();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void opcaoTrocarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTrocarContaActionPerformed
        // abre a tela de login para trocar o usuario
        this.controller.trocarUsuario();
    }//GEN-LAST:event_opcaoTrocarContaActionPerformed

    private void OpcaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoSairActionPerformed
        // sair do sistema
        dispose();
    }//GEN-LAST:event_OpcaoSairActionPerformed

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
            // insirir agenda
           controller.InsertAgendamento();
           iniciarAgenda();
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jButtonBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlunoActionPerformed
        //  Buscar por Nome:
        controller.atualizarTabelaPorPesquisa();
        
        
        
    }//GEN-LAST:event_jButtonBuscarAlunoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        //:
       
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // Refresh Agenda:
        iniciarAgenda();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTableAgendaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgendaAlunoMouseClicked
        // Pegando dados de tabela Alunos:
       
       
        
        
       
        
    }//GEN-LAST:event_jTableAgendaAlunoMouseClicked

    private void jComboBoxProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProfessorActionPerformed

    private void jButtonCancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAgendamentoActionPerformed
        // Cancelar agendamento:
        controller.excluirAgendamento();
        iniciarAgenda();
       
    }//GEN-LAST:event_jButtonCancelarAgendamentoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // Pesquisa por nome:
        controller.atualizarTabelaAgemdamentoPorPesquisa();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh1ActionPerformed
        // Atualizar Agenda:
        iniciarAgenda();
    }//GEN-LAST:event_jButtonRefresh1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu Opcao;
    private javax.swing.JMenuItem OpcaoSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarAluno;
    private javax.swing.JButton jButtonCancelarAgendamento;
    private javax.swing.JButton jButtonIprimir;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefresh1;
    private javax.swing.JComboBox<String> jComboBoxProfessor;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelProfessor;
    private javax.swing.JLabel jLabelTextAgendarAvaliacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPaneAgenda;
    private javax.swing.JScrollPane jScrollPaneAgendaMarcada;
    private javax.swing.JTable jTableAgendaAluno;
    private javax.swing.JTable jTableAgendaMarcados;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisarAgendamento;
    private javax.swing.JMenuItem opcaoTrocarConta;
    // End of variables declaration//GEN-END:variables
 
    
    public String armazenaNome(){
    String nome =  jTableAgendaAluno.getValueAt(jTableAgendaAluno.getSelectedRow(), 1).toString();
    
    return nome;
    
    }
    
        
    public Integer armazenaId(){
        Integer id = (Integer) jTableAgendaMarcados.getValueAt(jTableAgendaMarcados.getSelectedRow(),0);
        
        return id;
    }

    public JTextField getjTextFieldPesquisarAgendamento() {
        return jTextFieldPesquisarAgendamento;
    }

    public void setjTextFieldPesquisarAgendamento(JTextField jTextFieldPesquisarAgendamento) {
        this.jTextFieldPesquisarAgendamento = jTextFieldPesquisarAgendamento;
    }
    
    
    
    public JComboBox<String> getjComboBoxProfessor() {
        return jComboBoxProfessor;
    }

    public void setjComboBoxProfessor(JComboBox<String> jComboBoxProfessor) {
        this.jComboBoxProfessor = jComboBoxProfessor;
    }

    public JFormattedTextField getjFormattedTextFieldData() {
        return jFormattedTextFieldData;
    }

    public void setjFormattedTextFieldData(JFormattedTextField jFormattedTextFieldData) {
        this.jFormattedTextFieldData = jFormattedTextFieldData;
    }

    public JTable getjTableAgenda() {
        return jTableAgendaMarcados;
    }

    public void setjTableAgenda(JTable jTableAgenda) {
        this.jTableAgendaMarcados = jTableAgenda;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JTable getjTableAgendaAluno() {
        return jTableAgendaAluno;
    }

    public void setjTableAgendaAluno(JTable jTableAgendaAluno) {
        this.jTableAgendaAluno = jTableAgendaAluno;
    }
    

    private void iniciarAgenda() {
        controller.atualizarTabelaAluno();
        controller.atualizarBoxProfessor();
        controller.atualizarTabelaAgendamento();
        jTableAgendaAluno.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableAgendaMarcados.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
    }

    public JTable getjTableAgendaMarcados() {
        return jTableAgendaMarcados;
    }

    public void setjTableAgendaMarcados(JTable jTableAgendaMarcados) {
        this.jTableAgendaMarcados = jTableAgendaMarcados;
    }
    
    
    
    
     public final void fieldFormatDate(){
        try {
            MaskFormatter maskDate = new MaskFormatter("##/##/####  ##:##");
            maskDate.install(jFormattedTextFieldData);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo Idade", "ERRO", JOptionPane.ERROR);
        }
    }


}
