/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.AvaliacaoController;

/**
 *
 * @author renea
 */
public class Avaliacao extends javax.swing.JFrame {
    
    private final AvaliacaoController controller;
    
    
    /**
     * Creates new form Avalicao
     */
    public Avaliacao() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        controller = new AvaliacaoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextTreinos = new javax.swing.JLabel();
        jLabelTextPesqAluno = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonIprimir = new javax.swing.JButton();
        jTextFieldPesqAluno = new javax.swing.JTextField();
        jScrollPaneAvAluno = new javax.swing.JScrollPane();
        jTableAvAluno = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Opcao = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        opcaoTrocarConta = new javax.swing.JMenuItem();
        OpcaoSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextTreinos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTextTreinos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextTreinos.setText("Avaliação Alunos");
        getContentPane().add(jLabelTextTreinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabelTextPesqAluno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTextPesqAluno.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextPesqAluno.setText("Pesquisar Aluno");
        getContentPane().add(jLabelTextPesqAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jButtonIprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imprimir.png"))); // NOI18N
        getContentPane().add(jButtonIprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));
        getContentPane().add(jTextFieldPesqAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, -1));

        jScrollPaneAvAluno.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTableAvAluno.setAutoCreateRowSorter(true);
        jTableAvAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableAvAluno.setForeground(new java.awt.Color(102, 102, 102));
        jTableAvAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Renê Antunes", "36", "37", "30", "31", "60", "50", "65", "65", "66"},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Biceps Dir", "Biceps Esq", "Braço Dir", "Braço Esq", "Peitoral", "Barriga", "Costas", "Perna Dir", "Perna Esq"
            }
        ));
        jTableAvAluno.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPaneAvAluno.setViewportView(jTableAvAluno);

        getContentPane().add(jScrollPaneAvAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 850, 310));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGoundMenu (1).jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 35));

        Cadastro.setText("Matrículas");
        Cadastro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mulher.png"))); // NOI18N
        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treinador.png"))); // NOI18N
        jMenuItem2.setText("Professor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem2);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atuacao.png"))); // NOI18N
        jMenuItem8.setText("Admin");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem8);

        jMenuBar1.add(Cadastro);

        Opcao.setText("Opções");
        Opcao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agenda-icon.png"))); // NOI18N
        jMenuItem9.setText("Agenda");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Treino.png"))); // NOI18N
        jMenuItem10.setText("Treinos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Matricula.png"))); // NOI18N
        jMenuItem11.setText("Avaliação");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem11);

        opcaoTrocarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troca.png"))); // NOI18N
        opcaoTrocarConta.setText("Trocar de conta");
        opcaoTrocarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTrocarContaActionPerformed(evt);
            }
        });
        Opcao.add(opcaoTrocarConta);

        OpcaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        OpcaoSair.setText("Sair");
        OpcaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoSairActionPerformed(evt);
            }
        });
        Opcao.add(OpcaoSair);

        jMenuBar1.add(Opcao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Voltar ao menu principal:
        this.controller.voltarMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abre a aba Cadastrar Aluo

        this.controller.abrirCadAluno();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Abre a aba Cadastrar Professor
        this.controller.abrirCadProf();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //Abre a aba Cadastrar Adm
        this.controller.abrirCadAdm();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // Abre a aba Agenda

        this.controller.abrirAgendaAvali();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // Abre a aba Treinos

        this.controller.abrirTreinos();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // Abre a aba avaliação

        this.controller.abrirAvaliacao();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void opcaoTrocarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTrocarContaActionPerformed
        // abre a tela de login para trocar o usuario
        this.controller.trocarUsuario();
    }//GEN-LAST:event_opcaoTrocarContaActionPerformed

    private void OpcaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoSairActionPerformed
        // sair do sistema
        dispose();
    }//GEN-LAST:event_OpcaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avaliacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu Opcao;
    private javax.swing.JMenuItem OpcaoSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonIprimir;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTextPesqAluno;
    private javax.swing.JLabel jLabelTextTreinos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAvAluno;
    private javax.swing.JTable jTableAvAluno;
    private javax.swing.JTextField jTextFieldPesqAluno;
    private javax.swing.JMenuItem opcaoTrocarConta;
    // End of variables declaration//GEN-END:variables
}
