/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.CadastroAdmLogOffContoller;
import java.text.ParseException;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author renea
 */
public class CadastroAdmLogOff extends javax.swing.JFrame {
    
   private final CadastroAdmLogOffContoller  controller;

    /**
     * Creates new form CadastroAdmin
     */
    public CadastroAdmLogOff() {
        
        controller = new CadastroAdmLogOffContoller(this);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        fieldFormatDate();
        fieldFormatTel();
        fieldFormatCel();
        fieldFormatCPF();
        fieldFormatCEP();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelTextCadastroAdimin = new javax.swing.JLabel();
        jLabelTextName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTextEmail = new javax.swing.JLabel();
        jLabelTextCPF = new javax.swing.JLabel();
        jLabelTextCep = new javax.swing.JLabel();
        jTextFieldComplemento1 = new javax.swing.JTextField();
        jLabelTextComplemento = new javax.swing.JLabel();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jLabelTextNumero = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jFormattedTextFieldIdade = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTEL = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEL = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jRadioButtonWatssApp = new javax.swing.JRadioButton();
        jLabelTextSexo = new javax.swing.JLabel();
        jRadioButtonSexoM = new javax.swing.JRadioButton();
        jRadioButtonSexoF = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        mensagemCadastro = new javax.swing.JLabel();
        jLabelWatssApp = new javax.swing.JLabel();
        jLabelTextSenha = new javax.swing.JLabel();
        jLabelTextLogin1 = new javax.swing.JLabel();
        jLabelTextEndereco = new javax.swing.JLabel();
        jLabelTextBairro = new javax.swing.JLabel();
        jLabelTextEstado = new javax.swing.JLabel();
        jLabelTextIdade = new javax.swing.JLabel();
        jLabelTextCelular = new javax.swing.JLabel();
        jLabelTextCidade = new javax.swing.JLabel();
        jLabelTextTelefone1 = new javax.swing.JLabel();
        jLabelPanelBackGound = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opcao = new javax.swing.JMenu();
        opcaoTrocarConta = new javax.swing.JMenuItem();
        OpcaoSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 105, -1, -1));

        jLabelTextCadastroAdimin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTextCadastroAdimin.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCadastroAdimin.setText("Cadastro Adimin");
        getContentPane().add(jLabelTextCadastroAdimin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabelTextName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextName.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextName.setText("Nome");
        getContentPane().add(jLabelTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        jTextFieldName.setToolTipText("Nome");
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, -1));

        jLabelTextEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEmail.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEmail.setText("Email");
        getContentPane().add(jLabelTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabelTextCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCPF.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCPF.setText("CPF");
        jLabelTextCPF.setToolTipText("");
        getContentPane().add(jLabelTextCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabelTextCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCep.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCep.setText("CEP");
        getContentPane().add(jLabelTextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jTextFieldComplemento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplemento1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldComplemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 100, -1));

        jLabelTextComplemento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextComplemento.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextComplemento.setText("Compl");
        getContentPane().add(jLabelTextComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jTextFieldNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 100, -1));

        jLabelTextNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextNumero.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextNumero.setText("Número");
        getContentPane().add(jLabelTextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, -1));

        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, -1));

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 100, -1));

        jFormattedTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 100, -1));
        getContentPane().add(jFormattedTextFieldTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 130, -1));
        getContentPane().add(jFormattedTextFieldCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 120, -1));
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 120, -1));
        getContentPane().add(jFormattedTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 90, -1));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 130, -1));

        jRadioButtonWatssApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWatssAppActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonWatssApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, 20));

        jLabelTextSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextSexo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextSexo.setText("Sexo");
        getContentPane().add(jLabelTextSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        buttonGroupSexo.add(jRadioButtonSexoM);
        jRadioButtonSexoM.setText("M");
        jRadioButtonSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSexoMActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSexoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        buttonGroupSexo.add(jRadioButtonSexoF);
        jRadioButtonSexoF.setText("F");
        jRadioButtonSexoF.setToolTipText("");
        jRadioButtonSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSexoFActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSexoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 180, -1));

        mensagemCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mensagemCadastro.setText("       ");
        getContentPane().add(mensagemCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        jLabelWatssApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whatsapp.png"))); // NOI18N
        getContentPane().add(jLabelWatssApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabelTextSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextSenha.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextSenha.setText("Senha");
        getContentPane().add(jLabelTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabelTextLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextLogin1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextLogin1.setText("Login");
        getContentPane().add(jLabelTextLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabelTextEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEndereco.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEndereco.setText("Endereço");
        getContentPane().add(jLabelTextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabelTextBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextBairro.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextBairro.setText("Bairro");
        getContentPane().add(jLabelTextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabelTextEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEstado.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEstado.setText("Estado");
        getContentPane().add(jLabelTextEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jLabelTextIdade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextIdade.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextIdade.setText("Idade");
        getContentPane().add(jLabelTextIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jLabelTextCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCelular.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCelular.setText("Cel");
        getContentPane().add(jLabelTextCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabelTextCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCidade.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCidade.setText("Cidade");
        getContentPane().add(jLabelTextCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabelTextTelefone1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextTelefone1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextTelefone1.setText("Tel ");
        getContentPane().add(jLabelTextTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 30, -1));

        jLabelPanelBackGound.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPanelBackGound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/painelFundoCadastro.png"))); // NOI18N
        jLabelPanelBackGound.setToolTipText("");
        getContentPane().add(jLabelPanelBackGound, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 810, 490));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGoundMenu (1).jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 35));

        Opcao.setText("Opções");
        Opcao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        opcaoTrocarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troca.png"))); // NOI18N
        opcaoTrocarConta.setText("Trocar de conta");
        opcaoTrocarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTrocarContaActionPerformed(evt);
            }
        });
        Opcao.add(opcaoTrocarConta);

        OpcaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        OpcaoSair.setText("Sair");
        OpcaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoSairActionPerformed(evt);
            }
        });
        Opcao.add(OpcaoSair);

        jMenuBar1.add(Opcao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldComplemento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplemento1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldComplemento1ActionPerformed

    private void jTextFieldNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumero1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNumero1ActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jRadioButtonWatssAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWatssAppActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadioButtonWatssAppActionPerformed

    private void OpcaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoSairActionPerformed
        // sair do sistema
        dispose();
    }//GEN-LAST:event_OpcaoSairActionPerformed

    private void opcaoTrocarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTrocarContaActionPerformed
        // abre a tela de login para trocar o usuario
         controller.trocarUsuario();
       
    }//GEN-LAST:event_opcaoTrocarContaActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jRadioButtonSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSexoMActionPerformed
        // TODO add your handling code here:
        jRadioButtonSexoF.setSelected(false);
     
       
    }//GEN-LAST:event_jRadioButtonSexoMActionPerformed

    private void jRadioButtonSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSexoFActionPerformed
        // TODO add your handling code here:
        jRadioButtonSexoM.setSelected(false);
      
    }//GEN-LAST:event_jRadioButtonSexoFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.incluirUsuario();
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // Campo senha
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jFormattedTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdmLogOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdmLogOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdmLogOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdmLogOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdmLogOff().setVisible(true);
                
            }
        });
        
       
    }
    
    public void exibirCadAdm(){
       initComponents();
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opcao;
    private javax.swing.JMenuItem OpcaoSair;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEL;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldIdade;
    private javax.swing.JFormattedTextField jFormattedTextFieldTEL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPanelBackGound;
    private javax.swing.JLabel jLabelTextBairro;
    private javax.swing.JLabel jLabelTextCPF;
    private javax.swing.JLabel jLabelTextCadastroAdimin;
    private javax.swing.JLabel jLabelTextCelular;
    private javax.swing.JLabel jLabelTextCep;
    private javax.swing.JLabel jLabelTextCidade;
    private javax.swing.JLabel jLabelTextComplemento;
    private javax.swing.JLabel jLabelTextEmail;
    private javax.swing.JLabel jLabelTextEndereco;
    private javax.swing.JLabel jLabelTextEstado;
    private javax.swing.JLabel jLabelTextIdade;
    private javax.swing.JLabel jLabelTextLogin1;
    private javax.swing.JLabel jLabelTextName;
    private javax.swing.JLabel jLabelTextNumero;
    private javax.swing.JLabel jLabelTextSenha;
    private javax.swing.JLabel jLabelTextSexo;
    private javax.swing.JLabel jLabelTextTelefone1;
    private javax.swing.JLabel jLabelWatssApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonSexoF;
    private javax.swing.JRadioButton jRadioButtonSexoM;
    private javax.swing.JRadioButton jRadioButtonWatssApp;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JLabel mensagemCadastro;
    private javax.swing.JMenuItem opcaoTrocarConta;
    // End of variables declaration//GEN-END:variables
    
      String radio_sexo;
      String watsApp;
    
     public String getSexo(){
        if(jRadioButtonSexoF.isSelected()){
            radio_sexo = "F";
        
        }else{
            if (jRadioButtonSexoM.isSelected()){
                radio_sexo = "M";
            }
        }
        
        return  radio_sexo;
    }
    
    public String getWatsApp(){
        if (jRadioButtonWatssApp.isSelected()) {
            
            watsApp = "SIM";
          
        }else{
            watsApp = "NÃO";
        
        }
        return watsApp;
     }

    public ButtonGroup getButtonGroupSexo() {
        return buttonGroupSexo;
    }

    public void setButtonGroupSexo(ButtonGroup buttonGroupSexo) {
        this.buttonGroupSexo = buttonGroupSexo;
    }
     
     
    public JRadioButton getjRadioButtonSexoF() {
        return jRadioButtonSexoF;
    }

    public void setjRadioButtonSexoF(JRadioButton jRadioButtonSexoF) {
        this.jRadioButtonSexoF = jRadioButtonSexoF;
    }

    public JRadioButton getjRadioButtonSexoM() {
        return jRadioButtonSexoM;
    }

    public void setjRadioButtonSexoM(JRadioButton jRadioButtonSexoM) {
        this.jRadioButtonSexoM = jRadioButtonSexoM;
    }

    public JRadioButton getjRadioButtonWatssApp() {
        return jRadioButtonWatssApp;
    }

    public void setjRadioButtonWatssApp(JRadioButton jRadioButtonWatssApp) {
        this.jRadioButtonWatssApp = jRadioButtonWatssApp;
    }

    public JTextField getjTextFieldBairro() {
        return jTextFieldBairro;
    }

    public void setjTextFieldBairro(JTextField jTextFieldBairro) {
        this.jTextFieldBairro = jTextFieldBairro;
    }

    public JFormattedTextField getjFormattedTextFieldCPF() {
        return jFormattedTextFieldCPF;
    }

    public void setjFormattedTextFieldCPF(JFormattedTextField jFormattedTextFieldCPF) {
        this.jFormattedTextFieldCPF = jFormattedTextFieldCPF;
    }

    public JFormattedTextField getjFormattedTextFieldCEL() {
        return jFormattedTextFieldCEL;
    }

    public void setjFormattedTextFieldCEL(JFormattedTextField jFormattedTextFieldCEL) {
        this.jFormattedTextFieldCEL = jFormattedTextFieldCEL;
    }

    public JFormattedTextField getjFormattedTextFieldCEP() {
        return jFormattedTextFieldCEP;
    }

    public void setjFormattedTextFieldCEP(JFormattedTextField jFormattedTextFieldCEP) {
        this.jFormattedTextFieldCEP = jFormattedTextFieldCEP;
    }

    public JTextField getjTextFieldCidade() {
        return jTextFieldCidade;
    }

    public void setjTextFieldCidade(JTextField jTextFieldCidade) {
        this.jTextFieldCidade = jTextFieldCidade;
    }

    public JTextField getjTextFieldComplemento1() {
        return jTextFieldComplemento1;
    }

    public void setjTextFieldComplemento1(JTextField jTextFieldComplemento1) {
        this.jTextFieldComplemento1 = jTextFieldComplemento1;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldEndereco() {
        return jTextFieldEndereco;
    }

    public void setjTextFieldEndereco(JTextField jTextFieldEndereco) {
        this.jTextFieldEndereco = jTextFieldEndereco;
    }

    public JTextField getjTextFieldEstado() {
        return jTextFieldEstado;
    }

    public void setjTextFieldEstado(JTextField jTextFieldEstado) {
        this.jTextFieldEstado = jTextFieldEstado;
    }

    public JTextField getjTextFieldLogin() {
        return jTextFieldLogin;
    }

    public void setjTextFieldLogin(JTextField jTextFieldLogin) {
        this.jTextFieldLogin = jTextFieldLogin;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldNumero1() {
        return jTextFieldNumero1;
    }

    public void setjTextFieldNumero1(JTextField jTextFieldNumero1) {
        this.jTextFieldNumero1 = jTextFieldNumero1;
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public void setjPasswordField(JPasswordField jPasswordField) {
        this.jPasswordField = jPasswordField;
    }

    public JFormattedTextField getjFormattedTextFieldTEL() {
        return jFormattedTextFieldTEL;
    }

    public void setjFormattedTextFieldTEL(JFormattedTextField jFormattedTextFieldTEL) {
        this.jFormattedTextFieldTEL = jFormattedTextFieldTEL;
    }

    public JFormattedTextField getjFormattedTextFieldIdade() {
        return jFormattedTextFieldIdade;
    }

    public void setjFormattedTextFieldIdade(JFormattedTextField jFormattedTextFieldIdade) {
        this.jFormattedTextFieldIdade = jFormattedTextFieldIdade;
    }

      public final void fieldFormatDate(){
        try {
            MaskFormatter maskDate = new MaskFormatter("##/##/####");
            maskDate.install(jFormattedTextFieldIdade);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo Idade", "ERRO", JOptionPane.ERROR);
        }
    }
    
    public final void fieldFormatTel(){
        
        try {
            MaskFormatter maskTel = new MaskFormatter("(##)#####-####");
            maskTel.install(jFormattedTextFieldTEL);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao formatar campo Tel", "ERRO", JOptionPane.ERROR);
        }
    
    }
    
    public final void fieldFormatCel(){
    
     try {
            MaskFormatter maskCel = new MaskFormatter("(##)#####-####");
            maskCel.install(jFormattedTextFieldCEL);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao formatar campo Cel", "ERRO", JOptionPane.ERROR);
        }
    
    
    }
    
    public final void fieldFormatCPF(){
        
        try {
            MaskFormatter maskCPF = new MaskFormatter("###-###-###-##");
            maskCPF.install(jFormattedTextFieldCPF);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo CPF", "ERRO", JOptionPane.ERROR);
        }
        
    
    }
    
     public final void fieldFormatCEP(){
        
        try {
            MaskFormatter maskCEP = new MaskFormatter("#####-###");
            maskCEP.install(jFormattedTextFieldCEP);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo CEP", "ERRO", JOptionPane.ERROR);
        }
        
    
    }
  
}
