/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.LoginController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author renea
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;
   
    
   

    /**
     * Creates new form Login
     */
    public Login() {
       initComponents();
       controller = new LoginController(this);
       setLocationRelativeTo(null);
       setResizable(false);
        
     
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelTextPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelTextUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelTexLogin = new javax.swing.JLabel();
        jLabelPanelLogin = new javax.swing.JLabel();
        jLabelLogoLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 90, 30));

        jLabelTextPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTextPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextPassword.setText("Senha");
        getContentPane().add(jLabelTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 170, -1));

        jLabelTextUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextUser.setText("Usuário");
        getContentPane().add(jLabelTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 170, -1));

        jLabelTexLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTexLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexLogin.setText("Login");
        getContentPane().add(jLabelTexLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabelPanelLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPanelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/painel-login.png"))); // NOI18N
        getContentPane().add(jLabelPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 620, 490));

        jLabelLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGoundMenu (1).jpg"))); // NOI18N
        getContentPane().add(jLabelLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 620));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 35));

        Cadastro.setText("Cadastro");
        Cadastro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atuacao.png"))); // NOI18N
        jMenuItem4.setText("Admin");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem4);

        jMenuBar1.add(Cadastro);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
       
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Entrar no sistema
        controller.entrarNoSistema();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // cadastroAdm.exibirAdmin();

        controller.abrirCadAdmin();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:]
        
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelLogoLogin;
    private javax.swing.JLabel jLabelPanelLogin;
    private javax.swing.JLabel jLabelTexLogin;
    private javax.swing.JLabel jLabelTextPassword;
    private javax.swing.JLabel jLabelTextUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

   

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public void setjPasswordField(JPasswordField jPasswordField) {
        this.jPasswordField = jPasswordField;
    }

    public JTextField getjTextFieldUser() {
        return jTextFieldUser;
    }

    public void setjTextFieldUser(JTextField jTextFieldUser) {
        this.jTextFieldUser = jTextFieldUser;
    }

    
    
   
    

   

   
}
