/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.MatriculaProfessorController;
import java.text.ParseException;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author renea
 */
public class MatriculaProfessor extends javax.swing.JFrame {
    
    private final MatriculaProfessorController controller;
    
        
    /**
     * Creates new form CadastroProfessor
     */
    public MatriculaProfessor() {
        controller = new MatriculaProfessorController(this);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        fieldFormatDate();
        fieldFormatTel();
        fieldFormatCel();
        fieldFormatCPF();
        fieldFormatCEP();
        iniciarTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jRadioButtonWatssApp = new javax.swing.JRadioButton();
        jLabelCadastroProf = new javax.swing.JLabel();
        jLabelTextCep = new javax.swing.JLabel();
        jLabelTextName = new javax.swing.JLabel();
        jLabelTextEmail = new javax.swing.JLabel();
        jLabelTextCPF = new javax.swing.JLabel();
        jLabelTextIdade = new javax.swing.JLabel();
        jLabelTextComplemento = new javax.swing.JLabel();
        jLabelTextNumero = new javax.swing.JLabel();
        jLabelTextEndereco = new javax.swing.JLabel();
        jLabelTextBairro = new javax.swing.JLabel();
        jLabelTextCidade = new javax.swing.JLabel();
        jLabelTextEstado = new javax.swing.JLabel();
        jLabelTextTelefone = new javax.swing.JLabel();
        jLabelTextCelular = new javax.swing.JLabel();
        jLabelWatssApp = new javax.swing.JLabel();
        jLabelTextMensalidade = new javax.swing.JLabel();
        jLabelTextFormaDePagamento = new javax.swing.JLabel();
        jLabelTextSexo = new javax.swing.JLabel();
        jRadioButtonSexoM = new javax.swing.JRadioButton();
        jRadioButtonSexoF = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldComplemento1 = new javax.swing.JTextField();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jFormattedTextFieldIdade = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTEL = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEL = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jTextFieldPesquisarProf = new javax.swing.JTextField();
        jLabelTextPesquisar = new javax.swing.JLabel();
        jButtonBuscarAluno = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPaneTabelaProfessor = new javax.swing.JScrollPane();
        jTableTabelaProfessor = new javax.swing.JTable();
        jButtonCadastro = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Opcao = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        opcaoTrocarConta = new javax.swing.JMenuItem();
        OpcaoSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Manhã", "Tarde", "Noite", "Integral", " " }));
        jComboBoxHorario.setToolTipText("");
        jComboBoxHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 90, -1));

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Efetivo\t", "Temporário", " " }));
        getContentPane().add(jComboBoxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, -1));

        jRadioButtonWatssApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWatssAppActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonWatssApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, 20));

        jLabelCadastroProf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCadastroProf.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCadastroProf.setText("Matrícula Professor");
        getContentPane().add(jLabelCadastroProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 30));

        jLabelTextCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCep.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCep.setText("CEP");
        getContentPane().add(jLabelTextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jLabelTextName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextName.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextName.setText("Nome");
        getContentPane().add(jLabelTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, -1));

        jLabelTextEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEmail.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEmail.setText("Email");
        getContentPane().add(jLabelTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabelTextCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCPF.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCPF.setText("CPF");
        jLabelTextCPF.setToolTipText("");
        getContentPane().add(jLabelTextCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabelTextIdade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextIdade.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextIdade.setText("Nasc");
        getContentPane().add(jLabelTextIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        jLabelTextComplemento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextComplemento.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextComplemento.setText("Compl");
        getContentPane().add(jLabelTextComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabelTextNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextNumero.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextNumero.setText("Número");
        getContentPane().add(jLabelTextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabelTextEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEndereco.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEndereco.setText("Endereço");
        getContentPane().add(jLabelTextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabelTextBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextBairro.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextBairro.setText("Bairro");
        getContentPane().add(jLabelTextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabelTextCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCidade.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCidade.setText("Cidade");
        getContentPane().add(jLabelTextCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabelTextEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEstado.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEstado.setText("Estado");
        getContentPane().add(jLabelTextEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabelTextTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextTelefone.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextTelefone.setText("Tel ");
        getContentPane().add(jLabelTextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabelTextCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCelular.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCelular.setText("Cel");
        getContentPane().add(jLabelTextCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabelWatssApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whatsapp.png"))); // NOI18N
        getContentPane().add(jLabelWatssApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabelTextMensalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextMensalidade.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextMensalidade.setText("Horario");
        getContentPane().add(jLabelTextMensalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabelTextFormaDePagamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextFormaDePagamento.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextFormaDePagamento.setText("Cargo");
        getContentPane().add(jLabelTextFormaDePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabelTextSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextSexo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextSexo.setText("Sexo");
        getContentPane().add(jLabelTextSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        buttonGroupSexo.add(jRadioButtonSexoM);
        jRadioButtonSexoM.setText("M");
        getContentPane().add(jRadioButtonSexoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));

        buttonGroupSexo.add(jRadioButtonSexoF);
        jRadioButtonSexoF.setText("F");
        jRadioButtonSexoF.setToolTipText("");
        getContentPane().add(jRadioButtonSexoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jTextFieldName.setToolTipText("Nome");
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 160, -1));

        jTextFieldComplemento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplemento1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldComplemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 120, -1));

        jTextFieldNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 100, -1));
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, -1));

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 130, -1));

        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, -1));

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 120, -1));

        jFormattedTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 90, -1));
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 120, -1));
        getContentPane().add(jFormattedTextFieldTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));
        getContentPane().add(jFormattedTextFieldCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, -1));
        getContentPane().add(jFormattedTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 90, -1));

        jTextFieldPesquisarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarProfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, 30));

        jLabelTextPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTextPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextPesquisar.setText("Pesquisar");
        getContentPane().add(jLabelTextPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jButtonBuscarAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuscarAluno.setText("Buscar");
        jButtonBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 30));

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refersh.png"))); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 40, 30));

        jScrollPaneTabelaProfessor.setBackground(new java.awt.Color(217, 217, 217));

        jTableTabelaProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Professor", "Sexo", "Cel", "WP", "Tel", "E-mail", "CPF", "Nasc", "Endere", "Num", "Bairro", "Cidade", "Compl", "Estado", "CEP", "Turno", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTabelaProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaProfessorMouseClicked(evt);
            }
        });
        jScrollPaneTabelaProfessor.setViewportView(jTableTabelaProfessor);
        if (jTableTabelaProfessor.getColumnModel().getColumnCount() > 0) {
            jTableTabelaProfessor.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableTabelaProfessor.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(16).setPreferredWidth(100);
            jTableTabelaProfessor.getColumnModel().getColumn(17).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPaneTabelaProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 850, 130));

        jButtonCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastro.setText("Cadastrar");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setText("Deletar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 80, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Salvar Alteração");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGoundMenu (1).jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 35));

        Cadastro.setText("Matrículas");
        Cadastro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mulher.png"))); // NOI18N
        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treinador.png"))); // NOI18N
        jMenuItem2.setText("Professor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem2);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atuacao.png"))); // NOI18N
        jMenuItem8.setText("Admin");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem8);

        jMenuBar1.add(Cadastro);

        Opcao.setText("Opções");
        Opcao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agenda-icon.png"))); // NOI18N
        jMenuItem9.setText("Agenda");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Treino.png"))); // NOI18N
        jMenuItem10.setText("Treinos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Matricula.png"))); // NOI18N
        jMenuItem11.setText("Avaliação");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Opcao.add(jMenuItem11);

        opcaoTrocarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troca.png"))); // NOI18N
        opcaoTrocarConta.setText("Trocar de conta");
        opcaoTrocarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTrocarContaActionPerformed(evt);
            }
        });
        Opcao.add(opcaoTrocarConta);

        OpcaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        OpcaoSair.setText("Sair");
        OpcaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoSairActionPerformed(evt);
            }
        });
        Opcao.add(OpcaoSair);

        jMenuBar1.add(Opcao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonWatssAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWatssAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonWatssAppActionPerformed

    private void jComboBoxHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHorarioActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldComplemento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplemento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplemento1ActionPerformed

    private void jTextFieldNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumero1ActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Voltar ao menu principal:
        this.controller.voltarMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //Abre a aba Cadastrar Adm
        this.controller.abrirCadAdm();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Abre a aba Cadastrar Professor
        this.controller.abrirCadProf();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abre a aba Cadastrar Aluo

        this.controller.abrirCadAluno();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // Abre a aba Agenda

        this.controller.abrirAgendaAvali();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // Abre a aba Treinos

        this.controller.abrirTreinos();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // Abre a aba avaliação

        this.controller.abrirAvaliacao();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void opcaoTrocarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTrocarContaActionPerformed
        // abre a tela de login para trocar o usuario
        this.controller.trocarUsuario();
    }//GEN-LAST:event_opcaoTrocarContaActionPerformed

    private void OpcaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoSairActionPerformed
        // sair do sistema
        dispose();
    }//GEN-LAST:event_OpcaoSairActionPerformed

    private void jFormattedTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldIdadeActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldPesquisarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarProfActionPerformed

    private void jButtonBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlunoActionPerformed
        //  Buscar por Nome:
        controller.atualizarTabelaPorPesquisa();
        
    }//GEN-LAST:event_jButtonBuscarAlunoActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // Refresh Agenda:
        
        iniciarTabela();
        
       

    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTableTabelaProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaProfessorMouseClicked
        // Tabela mouse clicked:
        //         controller.editarCadAluno();

        MatriculaAluno viewCadAluno = new MatriculaAluno();
        viewCadAluno.getjTextFieldName()
        .setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(),1).toString());

    }//GEN-LAST:event_jTableTabelaProfessorMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Editar Cadastro Alunos:

        //O evento fará com que o usuario seja direcionado para tela semelhando ao cadastro
        // porém com todos os dados já preenchidos referente ao aluno escolhido e lá
        // poderá editar os dados desejados.
        setCamposProf();

        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        // TODO add your handling code here:
         controller.incluirProfessor();
         iniciarTabela();
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Salvar edição:        
        controller.alterarProf();
        iniciarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // Excluir professor:
        controller.exluirProf();
        iniciarTabela();
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriculaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu Opcao;
    private javax.swing.JMenuItem OpcaoSair;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarAluno;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEL;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldIdade;
    private javax.swing.JFormattedTextField jFormattedTextFieldTEL;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCadastroProf;
    private javax.swing.JLabel jLabelTextBairro;
    private javax.swing.JLabel jLabelTextCPF;
    private javax.swing.JLabel jLabelTextCelular;
    private javax.swing.JLabel jLabelTextCep;
    private javax.swing.JLabel jLabelTextCidade;
    private javax.swing.JLabel jLabelTextComplemento;
    private javax.swing.JLabel jLabelTextEmail;
    private javax.swing.JLabel jLabelTextEndereco;
    private javax.swing.JLabel jLabelTextEstado;
    private javax.swing.JLabel jLabelTextFormaDePagamento;
    private javax.swing.JLabel jLabelTextIdade;
    private javax.swing.JLabel jLabelTextMensalidade;
    private javax.swing.JLabel jLabelTextName;
    private javax.swing.JLabel jLabelTextNumero;
    private javax.swing.JLabel jLabelTextPesquisar;
    private javax.swing.JLabel jLabelTextSexo;
    private javax.swing.JLabel jLabelTextTelefone;
    private javax.swing.JLabel jLabelWatssApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButtonSexoF;
    private javax.swing.JRadioButton jRadioButtonSexoM;
    private javax.swing.JRadioButton jRadioButtonWatssApp;
    private javax.swing.JScrollPane jScrollPaneTabelaProfessor;
    private javax.swing.JTable jTableTabelaProfessor;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldPesquisarProf;
    private javax.swing.JMenuItem opcaoTrocarConta;
    // End of variables declaration//GEN-END:variables

    String radio_sexo;
      String watsApp;
    
     public String getSexo(){
        if(jRadioButtonSexoF.isSelected()){
            radio_sexo = "F";
        
        }else{
            if (jRadioButtonSexoM.isSelected()){
                radio_sexo = "M";
            }
        }
        
        return  radio_sexo;
    }
    
    public String getWatsApp(){
        if (jRadioButtonWatssApp.isSelected()) {
            
            watsApp = "SIM";
          
        }else{
            watsApp = "NÃO";
        
        }
        return watsApp;
     }
    
    private void setCamposProf(){
         jTextFieldName.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 1).toString());
         jTextFieldEmail.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 6).toString());
         jFormattedTextFieldCPF.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 7).toString());
         jTextFieldEndereco.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 9).toString());
         jTextFieldNumero1.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 10).toString());
         jTextFieldComplemento1.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 13).toString()); 
         jTextFieldBairro.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 11).toString()); 
         jTextFieldCidade.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 12).toString()); 
         jTextFieldEstado.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 14).toString());
         jFormattedTextFieldCEP.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 15).toString());
         jFormattedTextFieldTEL.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 5).toString());
         jFormattedTextFieldCEL.setText(jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(), 3).toString());
    }
    
     public Integer armazenaId(){
    
    Integer id =  (Integer) jTableTabelaProfessor.getValueAt(jTableTabelaProfessor.getSelectedRow(),0);
    return id;
    
    }
    
     private void iniciarTabela() {
        controller.atualizarTabelaProf();
        jTableTabelaProfessor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    public JTable getjTableTabelaProfessor() {
        return jTableTabelaProfessor;
    }

    public void setjTableTabelaProfessor(JTable jTableTabelaProfessor) {
        this.jTableTabelaProfessor = jTableTabelaProfessor;
    }

    public JTextField getjTextFieldPesquisarProf() {
        return jTextFieldPesquisarProf;
    }

    public void setjTextFieldPesquisarProf(JTextField jTextFieldPesquisarProf) {
        this.jTextFieldPesquisarProf = jTextFieldPesquisarProf;
    }

  
    
    

    public ButtonGroup getButtonGroupSexo() {
        return buttonGroupSexo;
    }

    public void setButtonGroupSexo(ButtonGroup buttonGroupSexo) {
        this.buttonGroupSexo = buttonGroupSexo;
    }

    public JComboBox<String> getjComboBoxCargo() {
        return jComboBoxCargo;
    }

    public void setjComboBoxCargo(JComboBox<String> jComboBoxCargo) {
        this.jComboBoxCargo = jComboBoxCargo;
    }

    public JComboBox<String> getjComboBoxHorario() {
        return jComboBoxHorario;
    }

    public void setjComboBoxHorario(JComboBox<String> jComboBoxHorario) {
        this.jComboBoxHorario = jComboBoxHorario;
    }
  
    public JRadioButton getjRadioButtonSexoF() {
        return jRadioButtonSexoF;
    }

    public void setjRadioButtonSexoF(JRadioButton jRadioButtonSexoF) {
        this.jRadioButtonSexoF = jRadioButtonSexoF;
    }

    public JRadioButton getjRadioButtonSexoM() {
        return jRadioButtonSexoM;
    }

    public void setjRadioButtonSexoM(JRadioButton jRadioButtonSexoM) {
        this.jRadioButtonSexoM = jRadioButtonSexoM;
    }

    public JRadioButton getjRadioButtonWatssApp() {
        return jRadioButtonWatssApp;
    }

    public void setjRadioButtonWatssApp(JRadioButton jRadioButtonWatssApp) {
        this.jRadioButtonWatssApp = jRadioButtonWatssApp;
    }

    public JTextField getjTextFieldBairro() {
        return jTextFieldBairro;
    }

    public JFormattedTextField getjFormattedTextFieldCEL() {
        return jFormattedTextFieldCEL;
    }

    public void setjFormattedTextFieldCEL(JFormattedTextField jFormattedTextFieldCEL) {
        this.jFormattedTextFieldCEL = jFormattedTextFieldCEL;
    }

    public JFormattedTextField getjFormattedTextFieldCPF() {
        return jFormattedTextFieldCPF;
    }

    public void setjFormattedTextFieldCPF(JFormattedTextField jFormattedTextFieldCPF) {
        this.jFormattedTextFieldCPF = jFormattedTextFieldCPF;
    }
    
    public void setjTextFieldBairro(JTextField jTextFieldBairro) {
        this.jTextFieldBairro = jTextFieldBairro;
    }

    public JLabel getjLabelTextCPF() {
        return jLabelTextCPF;
    }

    public void setjLabelTextCPF(JLabel jLabelTextCPF) {
        this.jLabelTextCPF = jLabelTextCPF;
    }

   

    public JTextField getjTextFieldCel() {
        return jTextFieldCidade;
    }

    public void setjTextFieldCel(JTextField jTextFieldCel) {
        this.jTextFieldCidade = jTextFieldCel;
    }

    public JFormattedTextField getjFormattedTextFieldCEP() {
        return jFormattedTextFieldCEP;
    }

    public void setjFormattedTextFieldCEP(JFormattedTextField jFormattedTextFieldCEP) {
        this.jFormattedTextFieldCEP = jFormattedTextFieldCEP;
    }

   

    public JTextField getjTextFieldComplemento1() {
        return jTextFieldComplemento1;
    }

    public void setjTextFieldComplemento1(JTextField jTextFieldComplemento1) {
        this.jTextFieldComplemento1 = jTextFieldComplemento1;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldEndereco() {
        return jTextFieldEndereco;
    }

    public void setjTextFieldEndereco(JTextField jTextFieldEndereco) {
        this.jTextFieldEndereco = jTextFieldEndereco;
    }

    public JTextField getjTextFieldEstado() {
        return jTextFieldEstado;
    }

    public void setjTextFieldEstado(JTextField jTextFieldEstado) {
        this.jTextFieldEstado = jTextFieldEstado;
    }

   

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldNumero1() {
        return jTextFieldNumero1;
    }

    public void setjTextFieldNumero1(JTextField jTextFieldNumero1) {
        this.jTextFieldNumero1 = jTextFieldNumero1;
    }

    public JFormattedTextField getjFormattedTextFieldTEL() {
        return jFormattedTextFieldTEL;
    }

    public void setjFormattedTextFieldTEL(JFormattedTextField jFormattedTextFieldTEL) {
        this.jFormattedTextFieldTEL = jFormattedTextFieldTEL;
    }

    public JTextField getjTextFieldCidade() {
        return jTextFieldCidade;
    }

    public void setjTextFieldCidade(JTextField jTextFieldCidade) {
        this.jTextFieldCidade = jTextFieldCidade;
    }

    public JFormattedTextField getjFormattedTextFieldIdade() {
        return jFormattedTextFieldIdade;
    }

    public void setjFormattedTextFieldIdade(JFormattedTextField jFormattedTextFieldIdade) {
        this.jFormattedTextFieldIdade = jFormattedTextFieldIdade;
    }

     public final void fieldFormatDate(){
        try {
            MaskFormatter maskDate = new MaskFormatter("##/##/####");
            maskDate.install(jFormattedTextFieldIdade);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo Idade", "ERRO", JOptionPane.ERROR);
        }
    }
    
    public final void fieldFormatTel(){
        
        try {
            MaskFormatter maskTel = new MaskFormatter("(##)#####-####");
            maskTel.install(jFormattedTextFieldTEL);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao formatar campo Tel", "ERRO", JOptionPane.ERROR);
        }
    
    }
    
    public final void fieldFormatCel(){
    
     try {
            MaskFormatter maskCel = new MaskFormatter("(##)#####-####");
            maskCel.install(jFormattedTextFieldCEL);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao formatar campo Cel", "ERRO", JOptionPane.ERROR);
        }
    
    
    }
    
    public final void fieldFormatCPF(){
        
        try {
            MaskFormatter maskCPF = new MaskFormatter("###-###-###-##");
            maskCPF.install(jFormattedTextFieldCPF);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo CPF", "ERRO", JOptionPane.ERROR);
        }
        
    
    }
    
     public final void fieldFormatCEP(){
        
        try {
            MaskFormatter maskCEP = new MaskFormatter("#####-###");
            maskCEP.install(jFormattedTextFieldCEP);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo CEP", "ERRO", JOptionPane.ERROR);
        }
        
    
    }

}
